# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models import Cat
from openapi_server.models.base_model_ import Model
from openapi_server import util


class CatsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cats=None):  # noqa: E501
        """CatsResponse - a model defined in OpenAPI

        :param cats: The cats of this CatsResponse.  # noqa: E501
        :type cats: List[Cat]
        """
        self.openapi_types = {
            'cats': List[Cat]
        }

        self.attribute_map = {
            'cats': 'cats'
        }

        self._cats = cats

    @classmethod
    def from_dict(cls, dikt) -> 'CatsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CatsResponse of this CatsResponse.  # noqa: E501
        :rtype: CatsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cats(self):
        """Gets the cats of this CatsResponse.

        List of cats  # noqa: E501

        :return: The cats of this CatsResponse.
        :rtype: List[Cat]
        """
        return self._cats

    @cats.setter
    def cats(self, cats):
        """Sets the cats of this CatsResponse.

        List of cats  # noqa: E501

        :param cats: The cats of this CatsResponse.
        :type cats: List[Cat]
        """

        self._cats = cats
